#!/bin/bash

echo "⚠️  SECURITY ALERT: .env files with credentials were found in git!"
echo ""
echo "This script will help you remove .env files from git tracking."
echo ""
echo "Steps to fix this security issue:"
echo ""
echo "1. First, remove the files from git (but keep them locally):"
echo "   git rm --cached .env"
echo "   git rm --cached .env.production"
echo ""
echo "2. Commit the removal:"
echo "   git commit -m 'Remove .env files from repository'"
echo ""
echo "3. Push the changes:"
echo "   git push"
echo ""
echo "⚠️  IMPORTANT: Your Supabase credentials have been exposed!"
echo "   You should:"
echo "   1. Go to your Supabase dashboard"
echo "   2. Regenerate your API keys"
echo "   3. Update your local .env file with the new keys"
echo ""
echo "4. To completely remove from git history (optional but recommended):"
echo "   git filter-branch --force --index-filter \\"
echo "     'git rm --cached --ignore-unmatch .env .env.production' \\"
echo "     --prune-empty --tag-name-filter cat -- --all"
echo ""
echo "   Then force push:"
echo "   git push origin --force --all"
echo ""
echo "Note: The .gitignore has been updated to prevent this in the future."